apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: ${CLUSTER_NAME}
  region: ${REGION}

iam:
  serviceAccounts:
    - metadata:
        name: ${SERVICE_ACCOUNT_NAME}
        namespace: ${SERVICE_ACCOUNT_NAMESPACE}
      # The attachPolicyARN needs to be constructed carefully
      attachPolicyARNs:
        - "arn:aws:iam::${ACCOUNT_ID}:policy/${POLICY_NAME}"
      # eksctl typically overrides/updates by default when applying a config.
      # The --override-existing-serviceaccounts flag might not be needed
      # or might be controlled by how eksctl handles applying config files.
      # We will rely on standard eksctl behavior when applying this config.
